// src/store/authStore.ts
// This file was generated by the project_setup.py script.

import { create } from 'zustand';
import { User as FirebaseUser } from 'firebase/auth';

interface AuthState {
  user: FirebaseUser | null;
  isLoading: boolean;
  error: string | null;
  setUser: (user: FirebaseUser | null) => void;
  setLoading: (loading: boolean) => void;
  setError: (error: string | null) => void;
}

export const useAuthStore = create<AuthState>((set) => ({
  user: null,
  isLoading: true,
  error: null,
  setUser: (user) => set({ user, isLoading: false, error: null }), // Corrected
  setLoading: (loading) => set({ isLoading: loading }),           // Corrected
  setError: (error) => set({ error, isLoading: false }),         // Corrected
}));
