// src/components/layout/Navbar.tsx
// This file was generated by the create_platform_shell.py script.
'use client';

import React from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { signOut } from 'firebase/auth';
import { auth } from '@/config/firebase';
import { useAuthStore } from '@/store/authStore';

export default function Navbar() {
  const { user, setUser, setLoading, setError } = useAuthStore();
  const router = useRouter();

  const handleLogout = async () => {
    setLoading(true);
    setError(null); // Clear previous errors
    try {
      await signOut(auth);
      setUser(null); // Clear user from Zustand store
      router.push('/login'); // Redirect to login page
    } catch (error: any) {
      console.error("Logout Error:", error);
      setError("Failed to logout. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <nav className="bg-gray-800 text-white p-4 shadow-md sticky top-0 z-50">
      <div className="container mx-auto flex justify-between items-center">
        <Link href="/" className="text-xl font-bold hover:text-gray-300 transition-colors">
          MGS CS Hub
        </Link>
        <div className="flex items-center space-x-4">
          {user ? (
            <>
              <span className="text-sm hidden sm:inline">Welcome, {user.email || 'User'}</span>
              <button
                onClick={handleLogout}
                className="bg-indigo-600 hover:bg-indigo-700 text-white py-2 px-3 rounded-md text-sm font-medium transition-colors"
              >
                Logout
              </button>
            </>
          ) : (
            <Link
              href="/login"
              className="bg-indigo-600 hover:bg-indigo-700 text-white py-2 px-3 rounded-md text-sm font-medium transition-colors"
            >
              Login
            </Link>
          )}
        </div>
      </div>
    </nav>
  );
}
