// src/app/(platform)/student/dashboard/page.tsx
// This file was generated by the create_platform_shell.py script.
'use client';

import React from 'react';
import { useAuthStore } from '@/store/authStore';

export default function StudentDashboardPage() {
  const { user } = useAuthStore();

  return (
    <div className="bg-white p-6 rounded-lg shadow-md">
      <h1 className="text-2xl sm:text-3xl font-bold text-green-700 mb-6">
        Student Dashboard
      </h1>
      {user && (
        <p className="text-lg text-gray-700 mb-2">
          Hello, <span className="font-semibold">{user.email || 'Student'}</span>!
        </p>
      )}
      <p className="mt-4 text-gray-600">
        Your assigned worksheets, upcoming deadlines, and recent feedback will be displayed here.
      </p>
      <div className="mt-6 border-t pt-6">
        <h2 className="text-xl font-semibold text-gray-800 mb-3">Current Assignments</h2>
        {/* Placeholder for assignment list */}
        <div className="bg-gray-50 p-4 rounded-lg">
          <p className="text-sm text-gray-500">No assignments yet. Check back soon!</p>
        </div>
      </div>
    </div>
  );
}
