// src/app/(platform)/teacher/dashboard/page.tsx
// This file was generated by the create_platform_shell.py script.
'use client';

import React from 'react';
import { useAuthStore } from '@/store/authStore'; 

export default function TeacherDashboardPage() {
  const { user } = useAuthStore();

  return (
    <div className="bg-white p-6 rounded-lg shadow-md">
      <h1 className="text-2xl sm:text-3xl font-bold text-indigo-700 mb-6">
        Teacher Dashboard
      </h1>
      {user && (
        <p className="text-lg text-gray-700 mb-2">
          Welcome back, <span className="font-semibold">{user.email}</span>!
        </p>
      )}
      <p className="mt-4 text-gray-600">
        This is where your class overviews, assignment management, and student progress tracking tools will appear.
      </p>
      <div className="mt-6 border-t pt-6">
        <h2 className="text-xl font-semibold text-gray-800 mb-3">Quick Actions</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {/* Placeholder for quick action links/buttons */}
          <div className="bg-indigo-50 p-4 rounded-lg hover:shadow-lg transition-shadow">
            <h3 className="font-medium text-indigo-600">Manage Classes</h3>
            <p className="text-sm text-gray-500 mt-1">View, create, or edit your classes.</p>
          </div>
          <div className="bg-green-50 p-4 rounded-lg hover:shadow-lg transition-shadow">
            <h3 className="font-medium text-green-600">Assign Work</h3>
            <p className="text-sm text-gray-500 mt-1">Browse resources and assign to students.</p>
          </div>
        </div>
      </div>
    </div>
  );
}
